### ISSUE TITLE
subNetwork scan not working

### ISSUE THREAD

**Issue by mastercho** [abdulr7mann/hackerEnv#4]
When i try to run subnet scan with hackerEnv -s 109.120.244.0/24 

I'm getting Invalid subnet

**Comment by abdulr7mann** [comment]
```hackerEnv -s 24``` or if you have multiple interfaces and want to specify one: ```hackerEnv -i eth0 -s 24```
I apologize on not clearing subnet usage. let me know if it works ^^

**Comment by abdulr7mann** [comment]
> 
> 
> When i try to run subnet scan with hackerEnv -s 109.120.244.0/24
> 
> I'm getting Invalid subnet

```hackerEnv -s 24``` or if you have multiple interfaces and want to specify one: ```hackerEnv -i eth0 -s 24```
 I updated the usage in readme and in the tool ^^
